name: Test Automatizados

# Configurar cuando se va a ejecutar el workflow
on:
  push:
    branches: [ "master" ]
    paths:
    - '.github/workflows/test-workflow-config.yml'
    - 'code/*'
    - 'tests/testthat/*'
  pull_request:
    branches: [ "master" ]
    paths:
    - '.github/workflows/test-workflow-config.yml'
    - 'code/*'
    - 'tests/testthat/*'
    
  # Permite ejectuar el workflow manualmente desde la pestaña de Actions
  workflow_dispatch:
  
jobs:
  tests:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: ['4.3.0']

    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Instalar dependencias
        run: Rscript -e "install.packages(c('testthat', 'here'))"
      - name: Ejecutar Tests
        run: Rscript -e "source('tests/testthat.R')"
